site_name: eugenechou/blog
pages:
- Home: index.md
- modern cpp: 
  - 準備: prepare.md
  - Usability: usability.md
- Laradock: laradock.md
theme: 
  name: material
  palette:
    primary: 'Teal'
    accent: 'Teal'